name: unit-tests
run-name: ${{ github.actor }} Unit tests
on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run tests
        run: |
          bash run_tests.sh
